SUPPORTED_SUFFIXES = {".md", ".txt", ".py"}

DEFAULT_CHUNK_SIZE = 500
DEFAULT_CHUNK_OVERLAP = 100

DEFAULT_MODEL_NAME = "mock-model"
DEFAULT_BASE_URL = "http://localhost:8000/v1"
DEFAULT_API_KEY = "EMPTY"

DEFAULT_DB_PATH = "data/codedoc.db"